name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: baruchstreks    # Your Azure Web App name
  PYTHON_VERSION: '3.11'             # Python version

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Collect static files
      - name: Collect static files
        run: python manage.py collectstatic --noinput
        env:
          BARUCHSTREKS_STORAGE_CONNECTION: ${{ secrets.BARUCHSTREKS_STORAGE_CONNECTION }}
          MAPY_CZ_API_KEY: ${{ secrets.MAPY_CZ_API_KEY }}
      
      # Create deployment package
      - name: Prepare artifact for deployment
        run: zip -r release.zip . -x "*.git*" "release.zip"
      
      # Upload artifact for deployment job
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    
    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      # Unzip artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Configure Azure Web App
      - name: Configure Azure Web App
        run: |
          # Set Python version
          az webapp config set --resource-group BaruchsTreks --name baruchstreks --linux-fx-version "PYTHON|3.11"
          
          # Configure environment variables
          az webapp config appsettings set --resource-group BaruchsTreks --name baruchstreks --settings \
            BARUCHSTREKS_STORAGE_CONNECTION="${{ secrets.BARUCHSTREKS_STORAGE_CONNECTION }}" \
            MAPY_CZ_API_KEY="${{ secrets.MAPY_CZ_API_KEY }}" \
            SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            DEBUG="False" \
            ALLOWED_HOSTS="baruchstreks.azurewebsites.net" \
            SCM_DO_BUILD_DURING_DEPLOYMENT="0"
          
          # Set startup command
          az webapp config set --resource-group BaruchsTreks --name baruchstreks --startup-file "python manage.py runserver 0.0.0.0:8000"

      - name: Install Python dependencies on target machine
        run: |
          pip install -r requirements.txt
          python manage.py migrate
      
      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
