name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: b-treks    # Your Azure Web App name
  AZURE_RESOURCE_GROUP: BaruchsTreks  # Your Azure Resource Group name
  AZURE_APP_PLAN: b-treks-plan  # Your App Service Plan name
  PYTHON_VERSION: '3.12'             # Python version

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Collect static files
      - name: Collect static files
        run: python manage.py collectstatic --noinput
        env:
          BARUCHSTREKS_STORAGE_CONNECTION: ${{ secrets.BARUCHSTREKS_STORAGE_CONNECTION }}
          MAPY_CZ_API_KEY: ${{ secrets.MAPY_CZ_API_KEY }}
      
      # Create deployment package
      - name: Prepare artifact for deployment
        run: |
          # List files to verify
          ls -la
          # Create the zip file
          zip -r release.zip ./* -x "*.git*"
      
      # Upload artifact for deployment job
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    
    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create App Service Plan and Web App if they don't exist
      - name: Create App Service Plan and Web App if they don't exist
        run: |
          # Check if the App Service Plan exists
          if ! az appservice plan show --name ${{ env.AZURE_APP_PLAN }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} &>/dev/null; then
            echo "Creating new App Service Plan: ${{ env.AZURE_APP_PLAN }}"
            az appservice plan create --name ${{ env.AZURE_APP_PLAN }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --sku F1 --is-linux
          else
            echo "App Service Plan ${{ env.AZURE_APP_PLAN }} already exists"
          fi
          
          # Check if the web app exists
          if ! az webapp show --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} &>/dev/null; then
            echo "Creating new web app: ${{ env.AZURE_WEBAPP_NAME }}"
            az webapp create --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_PLAN }} --runtime "PYTHON:3.12"
          else
            echo "Web app ${{ env.AZURE_WEBAPP_NAME }} already exists"
          fi

      # Configure Azure Web App
      - name: Configure Azure Web App
        run: |
          # Set Python version
          az webapp config set --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --linux-fx-version "PYTHON|3.12"
          
          # Configure environment variables
          az webapp config appsettings set --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --settings \
            BARUCHSTREKS_STORAGE_CONNECTION="${{ secrets.BARUCHSTREKS_STORAGE_CONNECTION }}" \
            MAPY_CZ_API_KEY="${{ secrets.MAPY_CZ_API_KEY }}" \
            SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            DEBUG="False" \
            ALLOWED_HOSTS="${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net" \
            DJANGO_SETTINGS_MODULE="baruchstreks.settings" \
            DISABLE_COLLECTSTATIC="true" \
            SCM_DO_BUILD_DURING_DEPLOYMENT="true"

      
      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: release.zip
