name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: baruchstreks    # set this to your application's name
  PYTHON_VERSION: '3.11'             # set this to the Python version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
        env:
          BARUCHSTREKS_STORAGE_CONNECTION: ${{ secrets.BARUCHSTREKS_STORAGE_CONNECTION }}
          MAPY_CZ_API_KEY: ${{ secrets.MAPY_CZ_API_KEY }}
      
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Configure Azure Web App
      - name: Configure Azure Web App
        run: |
          az webapp config set --resource-group BaruchsTreks --name baruchstreks --linux-fx-version "PYTHON|3.11"
          az webapp config appsettings set --resource-group BaruchsTreks --name baruchstreks --settings \
            BARUCHSTREKS_STORAGE_CONNECTION="${{ secrets.BARUCHSTREKS_STORAGE_CONNECTION }}" \
            MAPY_CZ_API_KEY="${{ secrets.MAPY_CZ_API_KEY }}" \
            SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            DEBUG="False" \
            ALLOWED_HOSTS="baruchstreks.azurewebsites.net" \
            SCM_DO_BUILD_DURING_DEPLOYMENT="false" \
            WEBSITE_WEBDEPLOY_USE_SCM="false"
          
      # Set startup command
      - name: Set startup command
        run: |
          az webapp config set --resource-group BaruchsTreks --name baruchstreks --startup-file "gunicorn baruchstreks.wsgi:application --bind=0.0.0.0:8000"
      
      # Create deployment package
      - name: Create deployment package
        run: |
          mkdir -p deployment
          # Copy specific files and directories instead of the entire directory
          cp -r *.py *.txt *.sh .deployment baruchstreks templates trips static deployment/
          # Exclude .git and other unnecessary directories
          cd deployment
          pip install -r requirements.txt --target=site-packages
          cp -r site-packages/* .
          rm -rf site-packages
          zip -r ../deployment.zip .
          cd ..
      
      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./deployment.zip
          type: zip
