name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: baruchstreks    # Your Azure Web App name
  PYTHON_VERSION: '3.11'             # Python version

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Collect static files
      - name: Collect static files
        run: python manage.py collectstatic --noinput
        env:
          BARUCHSTREKS_STORAGE_CONNECTION: ${{ secrets.BARUCHSTREKS_STORAGE_CONNECTION }}
          MAPY_CZ_API_KEY: ${{ secrets.MAPY_CZ_API_KEY }}

      # Configure App Service for Python
      - name: Configure App Service
        run: |
          az webapp config set --resource-group BaruchsTreks --name ${{ env.AZURE_WEBAPP_NAME }} --linux-fx-version "PYTHON|3.11"
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: production

